export const FETCH_QUESTIONS = 'FETCH_QUESTIONS';
export const FETCH_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS';
export const FETCH_QUESTIONS_ERROR = 'FETCH_QUESTIONS_ERROR';
export const SUBMIT_ANSWERS = 'SUBMIT_ANSWERS';
export const SET_RESPONSE = 'SET_RESPONSE';
export const FETCH_ANSWERS_ERROR = 'FETCH_ANSWERS_ERROR';
export const RESET_ALL = 'RESET_ALL';
export const SET_SETNUMBER = 'SET_SETNUMBER';

